<?php

/**
 * Implements hook_menu()
 * @return array
 */
function jslog_menu() {
  $items = array();
  $items['ajax/json/jslog'] = array (
    'title' => 'Ajax log',
    'page callback' => 'jslog_ajax_log',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  return $items;
}


/**
 * page_callback to be used ajax callback for jslog to send log messages.
 */
function jslog_ajax_log() {
  $severity = $_POST['severity'];
  $message = $_POST['message'];
  $excepton = $_POST['exception'];
  $data = $_POST['data'];

  if(!empty($severity) && !empty($message)) {
    watchdog('jslog', $message, null, $severity);
  }
}

/**
 * Implements hook_page_build
 * @param $page
 */
function jslog_page_build(&$page) {
  drupal_add_js(drupal_get_path('module','jslog') . '/js/jslog.js');
}

